services:
  - type: web
    name: ultrasearch-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      # We set sync: false so Render asks you to paste these securely in the dashboard
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
